stages:
  - build
  - publish
  - publish-to-npm

variables:
  NODE_IMAGE: "node:20.9.0"

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

build:
  image: $NODE_IMAGE
  stage: build
  tags:
    - build
  script:
    - npm run build
  only:
    - branches

publish:
  image: $NODE_IMAGE
  stage: publish
  tags:
    - build
  script:
    - npm i -f
    - npm version 0.0.0-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA} --no-git-tag-version --allow-same-version
    - npm run build
    - npm run test
    - npm config set //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm publish --registry https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/ --loglevel=info
  only:
    - branches

publish-to-npm:
  image: $NODE_IMAGE
  stage: publish-to-npm
  tags:
    - build
  script:
    - npm i -f
    - npm version $CI_COMMIT_TAG --no-git-tag-version --allow-same-version
    - npm run build
    - npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
    - npm publish --loglevel=info
  only:
    - tags
